# Generated by Django 5.0 on 2024-10-15 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timwise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlights',
            name='bookauthor',
            field=models.TextField(default='author'),
            preserve_default=False,
        ),
    ]
