# Generated by Django 5.0 on 2024-10-18 00:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timwise', '0002_highlights_bookauthor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('author_id', models.AutoField(primary_key=True, serialize=False)),
                ('author_last_name', models.CharField(max_length=30)),
                ('author_first_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='highlights',
            name='bookauthor',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='highlights',
            name='bookname',
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('bookname', models.CharField(max_length=60)),
                ('chapter_count', models.IntegerField()),
                ('year_written', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('bookauthor_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timwise.authors')),
            ],
        ),
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('highlight_ID', models.AutoField(primary_key=True, serialize=False)),
                ('highlight_chapter_number', models.CharField(max_length=6)),
                ('highlight_html_line_number', models.IntegerField()),
                ('highlight_color', models.CharField(max_length=30)),
                ('highlight_page_number', models.IntegerField()),
                ('highlight_text', models.TextField()),
                ('highlight_book_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timwise.books')),
            ],
        ),
    ]
