# Generated by Django 5.0 on 2024-10-18 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timwise', '0003_authors_alter_highlights_bookauthor_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Authors',
            new_name='Author',
        ),
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
    ]
