# Generated by Django 5.0 on 2024-10-19 02:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timwise', '0004_rename_authors_author_rename_books_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_first_name',
            field=models.CharField(max_length=30, verbose_name='author first name'),
        ),
        migrations.AlterField(
            model_name='author',
            name='author_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='author ID'),
        ),
        migrations.AlterField(
            model_name='author',
            name='author_last_name',
            field=models.CharField(max_length=30, verbose_name='author last name'),
        ),
        migrations.AlterField(
            model_name='book',
            name='bookauthor_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timwise.author', verbose_name='book author ID'),
        ),
        migrations.AlterField(
            model_name='book',
            name='chapter_count',
            field=models.IntegerField(verbose_name='chapter count'),
        ),
        migrations.AlterField(
            model_name='book',
            name='year_written',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)], verbose_name='year written'),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='highlight_ID',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='highlight ID'),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='highlight_book_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timwise.book', verbose_name='highlight chapter number'),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='highlight_color',
            field=models.CharField(max_length=30, verbose_name='highlight color'),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='highlight_html_line_number',
            field=models.IntegerField(verbose_name='highlight html line number'),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='highlight_page_number',
            field=models.IntegerField(verbose_name='highlight page number'),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='highlight_text',
            field=models.TextField(verbose_name='highlight text'),
        ),
    ]
