# Generated by Django 5.0 on 2024-10-19 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timwise', '0006_rename_author_id_author_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='highlights',
        ),
        migrations.RenameField(
            model_name='highlight',
            old_name='book_ID',
            new_name='bookID',
        ),
        migrations.RenameField(
            model_name='highlight',
            old_name='hapter_number',
            new_name='chapter_number',
        ),
    ]
