# Generated by Django 5.0 on 2024-10-21 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timwise', '0007_delete_highlights_rename_book_id_highlight_bookid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='files')),
            ],
        ),
    ]
