# Generated by Django 5.0 on 2024-11-02 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timwise', '0008_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='full_name',
            field=models.CharField(default='hfffhhg', max_length=30, verbose_name='author full name'),
            preserve_default=False,
        ),
    ]
