# Generated by Django 5.0 on 2024-11-03 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timwise', '0009_author_full_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-11-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='files',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
