# Generated by Django 5.0 on 2024-11-03 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timwise', '0010_files_uploaded_at_files_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='uploaded_at',
        ),
    ]
