# Generated by Django 5.0 on 2024-11-29 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timwise', '0012_files_uploaded_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='authorID',
            new_name='author',
        ),
    ]
