# Generated by Django 5.0 on 2024-11-30 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timwise', '0013_rename_authorid_book_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='highlight',
            old_name='bookID',
            new_name='book',
        ),
    ]
