# Generated by Django 5.0 on 2024-11-30 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timwise', '0014_rename_bookid_highlight_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='authorname',
        ),
    ]
