# Generated by Django 5.0 on 2024-11-30 18:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timwise', '0015_rename_author_book_authorname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='authorname',
        ),

        migrations.AlterField(
            model_name='book',
            name='year_written',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(9999)], verbose_name='year written'),
        ),
    ]
