# Generated by Django 5.0 on 2024-11-30 18:32

import django.db.models.deletion
import timwise.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timwise', '0016_remove_book_authorname_book_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='authortemp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='timwise.author', verbose_name='book author'),
        ),
    ]
