# Generated by Django 5.0 on 2024-11-30 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timwise', '0017_book_authortemp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='authortemp',
        ),
    ]
