# Generated by Django 5.0 on 2024-11-30 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timwise', '0022_rename_first_name_author_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
