# Generated by Django 5.0 on 2024-12-10 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timwise', '0023_alter_book_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlight',
            name='chapter_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='page_number',
            field=models.CharField(max_length=50, verbose_name='highlight page number'),
        ),
    ]
