# Generated by Django 5.0 on 2024-12-13 02:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timwise', '0024_alter_highlight_chapter_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='highlight',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=2222),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='highlight',
            name='session_key',
            field=models.CharField(default=1111, max_length=50, verbose_name='django session key'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='highlight',
            name='user',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
