# Generated by Django 5.0 on 2024-12-13 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timwise', '0025_highlight_date_added_highlight_session_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='highlight',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='highlight',
            name='session_key',
        ),
        migrations.RemoveField(
            model_name='highlight',
            name='user',
        ),
    ]
