# Generated by Django 5.0 on 2024-12-13 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timwise', '0027_highlight_dateadded_highlight_sessionkey_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlight',
            name='date',
            field=models.CharField(default=123, max_length=12, verbose_name='date'),
            preserve_default=False,
        ),
    ]
