# Generated by Django 5.0 on 2024-12-13 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timwise', '0028_highlight_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='highlight',
            old_name='dateadded',
            new_name='timestamp',
        ),
    ]
