# Generated by Django 5.0 on 2024-12-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timwise', '0029_rename_dateadded_highlight_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='dateloaded',
            field=models.CharField(default=111, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='dateloaded',
            field=models.CharField(default=111, max_length=12),
            preserve_default=False,
        ),
    ]
