# Generated by Django 5.0 on 2024-12-14 14:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timwise', '0030_author_dateloaded_book_dateloaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='sessionkey',
            field=models.CharField(default=111, max_length=50, verbose_name='django session key'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='sessionkey',
            field=models.CharField(default=111, max_length=50, verbose_name='django session key'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
