# Generated by Django 5.0 on 2024-12-14 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timwise', '0031_author_sessionkey_author_timestamp_book_sessionkey_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='highlight',
            old_name='date',
            new_name='dateloaded',
        ),
    ]
